-- =============================================================================
-- Consumer Setup (run after installing the app)
-- =============================================================================

-- Configuration
SET APP_NAME = 'YOUR_APP_NAME';
SET WAREHOUSE = 'YOUR_WAREHOUSE';
SET QLIK_MCP_SERVER = 'DB.SCHEMA.YOUR_QLIK_MCP_SERVER';
SET QLIK_INTEGRATION = 'YOUR_QLIK_MCP_INTEGRATION';
SET USER_ROLE = 'ACCOUNTADMIN';

USE ROLE ACCOUNTADMIN;

-- Grant caller privileges
GRANT CALLER USAGE ON WAREHOUSE IDENTIFIER($WAREHOUSE) TO APPLICATION IDENTIFIER($APP_NAME);
GRANT CALLER USAGE ON EXTERNAL MCP SERVER IDENTIFIER($QLIK_MCP_SERVER) TO APPLICATION IDENTIFIER($APP_NAME);

-- Grant application role
GRANT APPLICATION ROLE IDENTIFIER($APP_NAME || '.APP_USER') TO ROLE IDENTIFIER($USER_ROLE);

-- Register with Snowflake Intelligence
ALTER SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT
    ADD AGENT IDENTIFIER($APP_NAME || '.CORE.MY_AGENT');

-- Authenticate with Qlik
SELECT SYSTEM$START_USER_OAUTH_FLOW($QLIK_INTEGRATION);
