-- =============================================================================
-- Dual-Source Comparison Agent: Qlik MCP + Snowflake Semantic View
-- =============================================================================
--
-- This script creates a Cortex Agent that executes every user question against
-- TWO data sources and returns only a structured comparison of the results:
--   1. Qlik MCP — queries a Qlik Cloud app via the MCP server
--   2. Cortex Analyst — queries a Snowflake Semantic View
--
-- The agent reports: expression/SQL generated, tool call count, execution
-- duration, token consumption, and status for each path. Durations and token
-- counts are the agent's own ESTIMATES, not metered values. For metered usage,
-- see sql/cortex-agent-token-usage.sql.
--
-- What is created:
--   - Cortex Agent:  <TARGET_DATABASE>.<TARGET_SCHEMA>.<AGENT_NAME>
--
-- Prerequisites:
--   - An existing External MCP Server (created by create-mcp-agent.sql)
--   - An existing Semantic View over the target data
--   - The user must have completed OAuth for the Qlik MCP server:
--       SELECT SYSTEM$START_USER_OAUTH_FLOW('<integration_name>');
--   - ACCOUNTADMIN or a role with CREATE AGENT on the target schema
--
-- Usage:
--   1. Fill in the parameters in Step 0
--   2. Run the entire script in a Snowflake worksheet
--   3. The agent will appear in Snowflake Intelligence (CoWork)
--
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- =============================================================================
-- Step 0: Configuration Parameters
-- =============================================================================

-- Target location for the agent
SET TARGET_DATABASE    = 'CORTEX_DEMOS';
SET TARGET_SCHEMA      = 'PUBLIC';
SET AGENT_NAME         = 'TPCH_SF10';
SET AGENT_DISPLAY_NAME = 'TPCH_SF10';

-- Qlik MCP configuration
SET QLIK_MCP_SERVER_FQN = 'QLIK_MCP_DB.PUBLIC.qlik_mcp_server';  -- Fully qualified MCP server name
SET QLIK_APP_ID         = '<your-qlik-app-id>';                    -- Qlik Cloud app ID to query

-- Semantic View configuration
SET SEMANTIC_VIEW_FQN   = 'CORTEX_DEMOS.PUBLIC.SNOWFLAKE_SAMPLE_DATATPCH_SF10'; -- Fully qualified semantic view
SET ANALYST_WAREHOUSE   = 'COMPUTE';                                             -- Warehouse for Cortex Analyst execution

-- =============================================================================
-- Step 1: Create the Dual-Source Agent
-- =============================================================================

USE DATABASE IDENTIFIER($TARGET_DATABASE);
USE SCHEMA IDENTIFIER($TARGET_SCHEMA);

EXECUTE IMMEDIATE
$$
DECLARE
    v_agent_name VARCHAR;
    v_display_name VARCHAR;
    v_mcp_server VARCHAR;
    v_app_id VARCHAR;
    v_semantic_view VARCHAR;
    v_warehouse VARCHAR;
    v_spec VARCHAR;
    v_sql VARCHAR;
    -- The spec must be dollar-quoted, but a literal double-dollar anywhere in
    -- this block (even in a comment) would end the block early, so the
    -- delimiter is assembled at runtime.
    v_dq VARCHAR DEFAULT '$' || '$';
BEGIN
    SELECT GETVARIABLE('AGENT_NAME') INTO v_agent_name;
    SELECT GETVARIABLE('AGENT_DISPLAY_NAME') INTO v_display_name;
    SELECT GETVARIABLE('QLIK_MCP_SERVER_FQN') INTO v_mcp_server;
    SELECT GETVARIABLE('QLIK_APP_ID') INTO v_app_id;
    SELECT GETVARIABLE('SEMANTIC_VIEW_FQN') INTO v_semantic_view;
    SELECT GETVARIABLE('ANALYST_WAREHOUSE') INTO v_warehouse;

    v_spec := 'models:\n'
        || '  orchestration: auto\n'
        || '\n'
        || 'instructions:\n'
        || '  response: |\n'
        || '    You MUST ONLY return a structured comparison table. Do NOT return raw data results.\n'
        || '    Do NOT show the actual query output rows. ONLY show the metadata comparison between the two tools.\n'
        || '\n'
        || '    For every answer, return EXACTLY this format:\n'
        || '\n'
        || '    ## Comparison: [Question]\n'
        || '\n'
        || '    | Metric | Qlik MCP | Semantic View (Cortex Analyst) |\n'
        || '    |--------|----------|-------------------------------|\n'
        || '    | Expression / SQL | [Full Qlik expression used] | [Full SQL query generated] |\n'
        || '    | Tool calls | [number of tool calls made] | [number of tool calls made] |\n'
        || '    | Duration (seconds) | [execution time in seconds] | [execution time in seconds] |\n'
        || '    | Token consumption (est.) | [estimated input+output tokens] | [estimated input+output tokens] |\n'
        || '    | Status | [success / error / auth required] | [success / error] |\n'
        || '\n'
        || '    Rules:\n'
        || '    - ALWAYS show the complete Qlik expression (e.g., Sum(O_TOTALPRICE) with dimensions Year(O_ORDERDATE))\n'
        || '    - ALWAYS show the complete SQL generated by Cortex Analyst (the full query, not truncated)\n'
        || '    - Count every tool invocation separately (e.g., qlik_get_fields + qlik_create_data_object + qlik_get_chart_data = 3 calls)\n'
        || '    - Estimate token consumption based on input prompt size + output response size for each tool path\n'
        || '    - Duration should reflect wall-clock time from first tool call to last result for each path\n'
        || '    - If Qlik MCP requires authentication, show "Auth required" for expression and 0 for duration/tokens\n'
        || '    - Do NOT include the actual data rows in your response — only the comparison metadata above\n'
        || '\n'
        || '  orchestration: |\n'
        || '    You are a dual-source analytics agent with access to TWO data tools:\n'
        || '    1. Qlik MCP — connected to Qlik Cloud app ' || v_app_id || '\n'
        || '    2. TPCH_SF10_Analyst — Snowflake Cortex Analyst semantic view over ' || v_semantic_view || '\n'
        || '\n'
        || '    For EVERY user question, you MUST:\n'
        || '    1. First, attempt to answer using the Qlik MCP tools (scoped to app ' || v_app_id || ').\n'
        || '    2. Then, answer the same question using TPCH_SF10_Analyst (semantic view).\n'
        || '    3. Return ONLY the comparison table — never return raw data results.\n'
        || '\n'
        || '    Qlik MCP Tool Usage:\n'
        || '    - ALWAYS use app ID ' || v_app_id || '. Do NOT search for apps.\n'
        || '    - Use qlik_get_fields to discover available fields.\n'
        || '    - Use qlik_create_data_object to build hypercube queries with dimensions and measures.\n'
        || '    - Use qlik_get_chart_data to retrieve computed results.\n'
        || '    - Qlik expressions: Sum(FIELD), Count(FIELD), Avg(FIELD), Year(DATE_FIELD)\n'
        || '    - Qlik performs ALL calculations server-side. Never re-aggregate returned data.\n'
        || '    - Verify field values with qlik_get_field_values before applying selections.\n'
        || '    - Prefer set analysis over app-level selections for one-off queries.\n'
        || '    - Check qlik_list_measures and qlik_list_dimensions for governed master items tagged MCP before writing custom expressions.\n'
        || '\n'
        || '    Track and report:\n'
        || '    - The exact Qlik expression you used (dimensions + measures)\n'
        || '    - The exact SQL generated by Cortex Analyst\n'
        || '    - How many tool calls each path required\n'
        || '    - The elapsed time (in seconds) for each path\n'
        || '    - Estimated token consumption for each path (input tokens + output tokens)\n'
        || '\n'
        || '  sample_questions:\n'
        || '    - question: "What is the total order value (sum of o_totalprice) by order year?"\n'
        || '    - question: "How many customers are there per market segment (c_mktsegment)?"\n'
        || '    - question: "What is the average account balance (c_acctbal) by customer region?"\n'
        || '    - question: "What is the total quantity shipped (l_quantity) by ship mode (l_shipmode)?"\n'
        || '    - question: "What is the average discount (l_discount) by return flag (l_returnflag)?"\n'
        || '    - question: "What is the total extended price (l_extendedprice) by line status (l_linestatus)?"\n'
        || '    - question: "How many orders fall into each order priority (o_orderpriority)?"\n'
        || '    - question: "What is the average retail price (p_retailprice) by manufacturer (p_mfgr)?"\n'
        || '    - question: "What is the total available quantity (ps_availqty) and average supply cost (ps_supplycost) by part (partkey)?"\n'
        || '    - question: "How many orders per customer region?"\n'
        || '\n'
        || 'tools:\n'
        || '  - tool_spec:\n'
        || '      type: "cortex_analyst_text_to_sql"\n'
        || '      name: "TPCH_SF10_Analyst"\n'
        || '      description: "Answers questions about TPC-H SF10 structured data (customers, orders, lineitems, parts, suppliers, nations, regions) using the Snowflake semantic view with full relationship joins."\n'
        || 'mcp_servers:\n'
        || '  - server_spec:\n'
        || '      name: "' || v_mcp_server || '"\n'
        || 'tool_resources:\n'
        || '  TPCH_SF10_Analyst:\n'
        || '    semantic_view: "' || v_semantic_view || '"\n'
        || '    execution_environment:\n'
        || '      type: warehouse\n'
        || '      warehouse: "' || v_warehouse || '"\n';

    v_sql := 'CREATE OR REPLACE AGENT ' || v_agent_name
        || ' PROFILE = ''{"display_name": "' || v_display_name || '"}'''
        || ' FROM SPECIFICATION ' || v_dq || v_spec || v_dq;
    EXECUTE IMMEDIATE v_sql;
END;
$$;

-- =============================================================================
-- Step 2: Verify the Agent
-- =============================================================================

SELECT GET_DDL('CORTEX_AGENT', $TARGET_DATABASE || '.' || $TARGET_SCHEMA || '.' || $AGENT_NAME);
SHOW AGENTS IN SCHEMA IDENTIFIER($TARGET_DATABASE || '.' || $TARGET_SCHEMA);

-- =============================================================================
-- Step 3: Register with Snowflake Intelligence (optional)
-- =============================================================================

CREATE SNOWFLAKE INTELLIGENCE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT;

EXECUTE IMMEDIATE
$$
DECLARE
    v_agent_fqn VARCHAR;
BEGIN
    SELECT GETVARIABLE('TARGET_DATABASE') || '.' || GETVARIABLE('TARGET_SCHEMA') || '.' || GETVARIABLE('AGENT_NAME') INTO v_agent_fqn;
    EXECUTE IMMEDIATE 'ALTER SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT ADD AGENT ' || v_agent_fqn;
END;
$$;

-- =============================================================================
-- Step 4: Test the Agent
-- =============================================================================
-- Run a sample question; test_status should not be an error.

SELECT TRY_PARSE_JSON(
  SNOWFLAKE.CORTEX.DATA_AGENT_RUN(
    $TARGET_DATABASE || '.' || $TARGET_SCHEMA || '.' || $AGENT_NAME,
    $${"messages": [{"role": "user", "content": [{"type": "text", "text": "How many customers are there per market segment (c_mktsegment)?"}]}]}$$,
    TRUE
  )
):status::VARCHAR AS test_status;
