-- =============================================================================
-- MCP-First Agent with Semantic View Fallback
-- =============================================================================
--
-- This script creates a Cortex Agent that uses Qlik MCP as its PRIMARY tool
-- and falls back to a Snowflake Semantic View (Cortex Analyst) only when the
-- MCP path cannot answer the question.
--
-- Routing logic:
--   1. Every question is sent to Qlik MCP first.
--   2. If Qlik MCP returns an error, requires authentication, or the question
--      falls outside the Qlik app's data scope, the agent retries using the
--      Semantic View via Cortex Analyst.
--   3. The agent tells the user which source produced the answer.
--
-- What is created:
--   - Cortex Agent:  <TARGET_DATABASE>.<TARGET_SCHEMA>.<AGENT_NAME>
--
-- Prerequisites:
--   - An existing External MCP Server (created by create-mcp-agent.sql)
--   - An existing Semantic View over the target data
--   - The user must have completed OAuth for the Qlik MCP server:
--       SELECT SYSTEM$START_USER_OAUTH_FLOW('<integration_name>');
--   - ACCOUNTADMIN or a role with CREATE AGENT on the target schema
--
-- Usage:
--   1. Fill in the parameters in Step 0
--   2. Run the entire script in a Snowflake worksheet
--   3. The agent will appear in Snowflake Intelligence (CoWork)
--
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- =============================================================================
-- Step 0: Configuration Parameters
-- =============================================================================

-- Target location for the agent
SET TARGET_DATABASE    = 'CORTEX_DEMOS';
SET TARGET_SCHEMA      = 'PUBLIC';
SET AGENT_NAME         = 'MCP_FIRST_AGENT';
SET AGENT_DISPLAY_NAME = 'MCP-First Analytics Agent';

-- Qlik MCP configuration
SET QLIK_MCP_SERVER_FQN = 'QLIK_MCP_DB.PUBLIC.qlik_mcp_server';  -- Fully qualified MCP server name
SET QLIK_APP_ID         = '<your-qlik-app-id>';                    -- Qlik Cloud app ID to query

-- Semantic View (fallback) configuration
SET SEMANTIC_VIEW_FQN   = 'CORTEX_DEMOS.PUBLIC.SNOWFLAKE_SAMPLE_DATATPCH_SF10'; -- Fully qualified semantic view
SET ANALYST_WAREHOUSE   = 'COMPUTE';                                             -- Warehouse for Cortex Analyst execution

-- =============================================================================
-- Step 1: Create the MCP-First Fallback Agent
-- =============================================================================

USE DATABASE IDENTIFIER($TARGET_DATABASE);
USE SCHEMA IDENTIFIER($TARGET_SCHEMA);

EXECUTE IMMEDIATE
$$
DECLARE
    v_agent_name VARCHAR;
    v_display_name VARCHAR;
    v_mcp_server VARCHAR;
    v_app_id VARCHAR;
    v_semantic_view VARCHAR;
    v_warehouse VARCHAR;
    v_spec VARCHAR;
    v_sql VARCHAR;
BEGIN
    SELECT GETVARIABLE('AGENT_NAME') INTO v_agent_name;
    SELECT GETVARIABLE('AGENT_DISPLAY_NAME') INTO v_display_name;
    SELECT GETVARIABLE('QLIK_MCP_SERVER_FQN') INTO v_mcp_server;
    SELECT GETVARIABLE('QLIK_APP_ID') INTO v_app_id;
    SELECT GETVARIABLE('SEMANTIC_VIEW_FQN') INTO v_semantic_view;
    SELECT GETVARIABLE('ANALYST_WAREHOUSE') INTO v_warehouse;

    v_spec := 'models:\n'
        || '  orchestration: auto\n'
        || '\n'
        || 'instructions:\n'
        || '  response: |\n'
        || '    You are an analytics agent with TWO data tools: Qlik MCP (primary) and a Snowflake\n'
        || '    Semantic View (fallback). You MUST always try Qlik MCP first before using the fallback.\n'
        || '\n'
        || '    ## Source attribution\n'
        || '    Always tell the user which source produced the answer:\n'
        || '    - If answered by Qlik MCP: begin with **Source: Qlik MCP**\n'
        || '    - If answered by Semantic View fallback: begin with **Source: Snowflake Semantic View (fallback)**\n'
        || '      and include a one-line reason why Qlik MCP could not answer.\n'
        || '\n'
        || '    ## Presenting results\n'
        || '    - Present data clearly using tables when appropriate.\n'
        || '    - When using Qlik MCP, include the Qlik expression used (dimensions + measures).\n'
        || '    - When using the Semantic View, include the SQL query generated by Cortex Analyst.\n'
        || '    - Let Qlik handle all calculations — never re-aggregate data returned by Qlik.\n'
        || '\n'
        || '  orchestration: |\n'
        || '    You have access to two data tools. Follow this strict resolution order:\n'
        || '\n'
        || '    ## Step 1: Try Qlik MCP (PRIMARY)\n'
        || '    For every user question, FIRST attempt to answer using the Qlik MCP tools\n'
        || '    scoped to app ' || v_app_id || '.\n'
        || '\n'
        || '    Qlik MCP tool workflow:\n'
        || '    1. Use qlik_get_fields to discover available fields in app ' || v_app_id || '.\n'
        || '    2. Check qlik_list_measures and qlik_list_dimensions for governed master items\n'
        || '       tagged MCP — prefer these over custom expressions.\n'
        || '    3. Use qlik_create_data_object to build hypercube queries with dimensions and measures.\n'
        || '    4. Use qlik_get_chart_data to retrieve computed results.\n'
        || '    5. Verify field values with qlik_get_field_values before applying selections.\n'
        || '    6. Prefer set analysis over app-level selections for one-off queries.\n'
        || '    ALWAYS use app ID ' || v_app_id || '. Do NOT search for apps.\n'
        || '\n'
        || '    ## Step 2: Fall back to Semantic View (SECONDARY)\n'
        || '    Switch to the Snowflake_Analyst tool ONLY when:\n'
        || '    - Qlik MCP returns an authentication error (user has not completed OAuth)\n'
        || '    - Qlik MCP tools fail or return an error for the query\n'
        || '    - The requested data is clearly outside the scope of the Qlik app\n'
        || '      (e.g., fields that do not exist in the Qlik app)\n'
        || '    - Qlik MCP returns empty results and the semantic view is likely to have the data\n'
        || '\n'
        || '    When falling back, briefly note why Qlik MCP could not answer, then proceed\n'
        || '    with the Snowflake_Analyst tool.\n'
        || '\n'
        || '    ## Rules\n'
        || '    - NEVER skip Qlik MCP and go directly to the Semantic View.\n'
        || '    - NEVER query both sources for the same question (this is not a comparison agent).\n'
        || '    - If Qlik MCP answers successfully, do NOT also query the Semantic View.\n'
        || '\n'
        || '  sample_questions:\n'
        || '    - question: "What is the total order value by order year?"\n'
        || '    - question: "How many customers are there per market segment?"\n'
        || '    - question: "What is the average account balance by customer region?"\n'
        || '    - question: "What is the total quantity shipped by ship mode?"\n'
        || '    - question: "Show me the top 10 customers by total spending"\n'
        || '\n'
        || 'tools:\n'
        || '  - tool_spec:\n'
        || '      type: "cortex_analyst_text_to_sql"\n'
        || '      name: "Snowflake_Analyst"\n'
        || '      description: "Fallback tool — answers questions about structured data using the Snowflake semantic view. Use ONLY when Qlik MCP cannot answer."\n'
        || 'mcp_servers:\n'
        || '  - server_spec:\n'
        || '      name: "' || v_mcp_server || '"\n'
        || 'tool_resources:\n'
        || '  Snowflake_Analyst:\n'
        || '    semantic_view: "' || v_semantic_view || '"\n'
        || '    execution_environment:\n'
        || '      type: warehouse\n'
        || '      warehouse: "' || v_warehouse || '"\n';

    v_sql := 'CREATE OR REPLACE AGENT ' || v_agent_name
        || ' PROFILE = ''{"display_name": "' || v_display_name || '"}'''
        || ' FROM SPECIFICATION $$ ' || v_spec || ' $$';
    EXECUTE IMMEDIATE v_sql;
END;
$$;

-- =============================================================================
-- Step 2: Verify the Agent
-- =============================================================================

SELECT GET_DDL('CORTEX_AGENT', $TARGET_DATABASE || '.' || $TARGET_SCHEMA || '.' || $AGENT_NAME);
SHOW AGENTS IN SCHEMA IDENTIFIER($TARGET_DATABASE || '.' || $TARGET_SCHEMA);

-- =============================================================================
-- Step 3: Register with Snowflake Intelligence (optional)
-- =============================================================================

CREATE SNOWFLAKE INTELLIGENCE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT;

EXECUTE IMMEDIATE
$$
DECLARE
    v_agent_fqn VARCHAR;
BEGIN
    SELECT GETVARIABLE('TARGET_DATABASE') || '.' || GETVARIABLE('TARGET_SCHEMA') || '.' || GETVARIABLE('AGENT_NAME') INTO v_agent_fqn;
    EXECUTE IMMEDIATE 'ALTER SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT ADD AGENT ' || v_agent_fqn;
END;
$$;

-- =============================================================================
-- Step 4: Test the Agent
-- =============================================================================

-- 4a. Test that Qlik MCP is used as the primary source
SELECT TRY_PARSE_JSON(
  SNOWFLAKE.CORTEX.DATA_AGENT_RUN(
    $TARGET_DATABASE || '.' || $TARGET_SCHEMA || '.' || $AGENT_NAME,
    $${"messages": [{"role": "user", "content": [{"type": "text", "text": "How many customers are there per market segment?"}]}]}$$,
    TRUE
  )
):status::VARCHAR AS test_status;

-- 4b. Test fallback (use a question that references fields outside the Qlik app)
-- SELECT TRY_PARSE_JSON(
--   SNOWFLAKE.CORTEX.DATA_AGENT_RUN(
--     $TARGET_DATABASE || '.' || $TARGET_SCHEMA || '.' || $AGENT_NAME,
--     $${"messages": [{"role": "user", "content": [{"type": "text", "text": "What is the average supply cost by nation?"}]}]}$$,
--     TRUE
--   )
-- ):status::VARCHAR AS test_fallback_status;

-- =============================================================================
-- Cleanup (run manually when done)
-- =============================================================================
-- DROP AGENT MCP_FIRST_AGENT;
