-- =============================================================================
-- Cortex Agent Token & Credit Usage Inspector
-- =============================================================================
--
-- Breaks down Cortex Agent consumption by agent, service layer and LLM model,
-- including the input / output / cache token split and the warehouse credits
-- burned by the SQL those agents generated.
--
-- View used:
--   SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AGENT_USAGE_HISTORY
--
-- Shape of the granular columns (one array element per sub-request):
--   TOKENS_GRANULAR / CREDITS_GRANULAR =
--     [ { "<sub_request_id>": { "<service_type>": { "<model>": { "input": .., "output": ..,
--                                                               "cache_read_input": ..,
--                                                               "cache_write_input": .. } } },
--         "start_time": "..." }, ... ]
--   The two arrays are positionally aligned, so one FLATTEN chain over
--   CREDITS_GRANULAR plus a positional GET() into TOKENS_GRANULAR is enough.
--
-- Columns returned:
--   AGENT_DATABASE_NAME/SCHEMA/NAME — agent identity ('(no agent)' for direct
--                                     REST / Cortex Analyst calls with no agent object)
--   SERVICE_TYPE                   — cortex_agents, cortex_analyst, ...
--   MODEL_NAME                     — LLM used (claude-opus-4-8, claude-3-5-sonnet, ...)
--   TOKEN_CREDITS                  — AI credits for inference (NOT dollars)
--   TOTAL_TOKENS + the 4-way split — input / output / cache_read / cache_write
--   CACHE_READ_PCT                 — share of input tokens served from cache
--   REQUEST_COUNT / SUB_REQUEST_COUNT
--   AVG_TOKENS_PER_REQUEST, CREDITS_PER_1M_TOKENS
--
-- Prerequisites:
--   - A role with access to SNOWFLAKE.ACCOUNT_USAGE (ACCOUNTADMIN or a role
--     granted the GOVERNANCE_VIEWER / privileges on the SNOWFLAKE database)
--   - Cortex Agents invoked within the time window
--
-- Notes:
--   - ACCOUNT_USAGE views have latency (typically up to ~2h); very recent
--     activity may be missing.
--   - TOKEN_CREDITS covers inference only. SQL generated by the agent runs on a
--     warehouse and is billed separately — see WAREHOUSE_CREDITS in query 2.
--
-- HOW TO RUN:
--   This file contains three independent statements after the SET block. Most
--   clients (Snowsight, snow sql) only display the LAST result set, so run each
--   statement on its own — in Snowsight put the cursor inside a statement and
--   press Cmd/Ctrl+Enter. The SET variables persist for the session, so execute
--   them once first. The main per-agent/model breakdown is query 3, placed last
--   so that it is the result shown when the whole file is executed at once.
--
-- =============================================================================

-- Time window. Defaults to the last 30 days; override with explicit timestamps.
SET START_TIME = DATEADD('day', -30, CURRENT_TIMESTAMP());
SET END_TIME   = CURRENT_TIMESTAMP();
-- e.g. SET START_TIME = '2026-07-21'::TIMESTAMP_LTZ;
--      SET END_TIME   = '2026-08-21'::TIMESTAMP_LTZ;


-- -----------------------------------------------------------------------------
-- 1. Reconciliation check — run this to prove the flatten logic is lossless.
--    granular_* must equal header_* (tiny float drift on credits is expected).
-- -----------------------------------------------------------------------------
WITH granular AS (
    SELECT
        mdl.value AS credit_detail,
        GET(GET(GET(GET(h.TOKENS_GRANULAR, elem.index), sub.key), svc.key), mdl.key) AS token_detail
    FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AGENT_USAGE_HISTORY h,
         LATERAL FLATTEN(input => h.CREDITS_GRANULAR) elem,
         LATERAL FLATTEN(input => elem.value)         sub,
         LATERAL FLATTEN(input => sub.value)          svc,
         LATERAL FLATTEN(input => svc.value)          mdl
    WHERE sub.key <> 'start_time'
      AND h.START_TIME >= $START_TIME
      AND h.START_TIME <  $END_TIME
),
header AS (
    SELECT SUM(TOKENS) AS tokens, SUM(TOKEN_CREDITS) AS credits
    FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AGENT_USAGE_HISTORY
    WHERE START_TIME >= $START_TIME AND START_TIME < $END_TIME
)
SELECT
    (SELECT SUM(COALESCE(token_detail:input::NUMBER, 0) +
                COALESCE(token_detail:output::NUMBER, 0) +
                COALESCE(token_detail:cache_read_input::NUMBER, 0) +
                COALESCE(token_detail:cache_write_input::NUMBER, 0)) FROM granular) AS granular_tokens,
    (SELECT tokens FROM header)                                                      AS header_tokens,
    ROUND((SELECT SUM(COALESCE(credit_detail:input::FLOAT, 0) +
                      COALESCE(credit_detail:output::FLOAT, 0) +
                      COALESCE(credit_detail:cache_read_input::FLOAT, 0) +
                      COALESCE(credit_detail:cache_write_input::FLOAT, 0)) FROM granular), 6) AS granular_credits,
    ROUND((SELECT credits FROM header), 6)                                           AS header_credits,
    (SELECT COUNT_IF(token_detail IS NULL) FROM granular)                            AS unmatched_token_rows;


-- -----------------------------------------------------------------------------
-- 2. Total cost of ownership per agent: inference + warehouse + AI functions
--    TOKEN_CREDITS alone understates what an agent actually costs.
-- -----------------------------------------------------------------------------
SELECT
    COALESCE(AGENT_DATABASE_NAME, '(no agent)') AS agent_database_name,
    COALESCE(AGENT_SCHEMA_NAME,   '(no agent)') AS agent_schema_name,
    COALESCE(AGENT_NAME,          '(no agent)') AS agent_name,
    COUNT(*)                                                      AS request_count,
    COUNT(DISTINCT USER_NAME)                                     AS distinct_users,
    ROUND(SUM(TOKEN_CREDITS), 4)                                  AS inference_credits,
    ROUND(SUM(COALESCE(METADATA:sql_query_credits::FLOAT, 0)), 4) AS warehouse_credits,
    ROUND(SUM(COALESCE(METADATA:ai_functions_credits::FLOAT, 0)), 4) AS ai_function_credits,
    ROUND(SUM(TOKEN_CREDITS
              + COALESCE(METADATA:sql_query_credits::FLOAT, 0)
              + COALESCE(METADATA:ai_functions_credits::FLOAT, 0)), 4) AS total_credits,
    ROUND(AVG(TOKENS))                                            AS avg_tokens_per_request,
    -- END_TIME is not always populated; latency is averaged over the rows that
    -- have it, so check LATENCY_SAMPLE_SIZE before trusting AVG_LATENCY_SEC.
    ROUND(AVG(DATEDIFF('millisecond', START_TIME, END_TIME)) / 1000.0, 2) AS avg_latency_sec,
    COUNT_IF(END_TIME IS NOT NULL)                                AS latency_sample_size
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AGENT_USAGE_HISTORY
WHERE START_TIME >= $START_TIME
  AND START_TIME <  $END_TIME
GROUP BY ALL
ORDER BY total_credits DESC;


-- -----------------------------------------------------------------------------
-- 3. Token & credit breakdown by agent / service / model
-- -----------------------------------------------------------------------------
WITH granular AS (
    SELECT
        h.REQUEST_ID,
        COALESCE(h.AGENT_DATABASE_NAME, '(no agent)') AS agent_database_name,
        COALESCE(h.AGENT_SCHEMA_NAME,   '(no agent)') AS agent_schema_name,
        COALESCE(h.AGENT_NAME,          '(no agent)') AS agent_name,
        sub.key   AS sub_request_id,
        svc.key   AS service_type,
        mdl.key   AS model_name,
        mdl.value AS credit_detail,
        -- positional lookup into the aligned TOKENS_GRANULAR array
        GET(GET(GET(GET(h.TOKENS_GRANULAR, elem.index), sub.key), svc.key), mdl.key) AS token_detail
    FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AGENT_USAGE_HISTORY h,
         LATERAL FLATTEN(input => h.CREDITS_GRANULAR) elem,
         LATERAL FLATTEN(input => elem.value)         sub,
         LATERAL FLATTEN(input => sub.value)          svc,
         LATERAL FLATTEN(input => svc.value)          mdl
    WHERE sub.key <> 'start_time'          -- sibling key alongside the sub-request id
      AND h.START_TIME >= $START_TIME
      AND h.START_TIME <  $END_TIME
)
SELECT
    agent_database_name,
    agent_schema_name,
    agent_name,
    service_type,
    model_name,

    ROUND(SUM(
        COALESCE(credit_detail:input::FLOAT, 0) +
        COALESCE(credit_detail:output::FLOAT, 0) +
        COALESCE(credit_detail:cache_read_input::FLOAT, 0) +
        COALESCE(credit_detail:cache_write_input::FLOAT, 0)
    ), 4)                                                        AS token_credits,

    SUM(COALESCE(token_detail:input::NUMBER, 0))                 AS input_tokens,
    SUM(COALESCE(token_detail:output::NUMBER, 0))                AS output_tokens,
    SUM(COALESCE(token_detail:cache_read_input::NUMBER, 0))      AS cache_read_tokens,
    SUM(COALESCE(token_detail:cache_write_input::NUMBER, 0))     AS cache_write_tokens,
    SUM(COALESCE(token_detail:input::NUMBER, 0) +
        COALESCE(token_detail:output::NUMBER, 0) +
        COALESCE(token_detail:cache_read_input::NUMBER, 0) +
        COALESCE(token_detail:cache_write_input::NUMBER, 0))     AS total_tokens,

    -- cache effectiveness: high = prompt caching is working
    ROUND(100 * DIV0(
        SUM(COALESCE(token_detail:cache_read_input::NUMBER, 0)),
        SUM(COALESCE(token_detail:input::NUMBER, 0) +
            COALESCE(token_detail:cache_read_input::NUMBER, 0))
    ), 1)                                                        AS cache_read_pct,

    COUNT(DISTINCT REQUEST_ID)                                   AS request_count,
    COUNT(DISTINCT sub_request_id)                               AS sub_request_count,

    ROUND(DIV0(
        SUM(COALESCE(token_detail:input::NUMBER, 0) +
            COALESCE(token_detail:output::NUMBER, 0) +
            COALESCE(token_detail:cache_read_input::NUMBER, 0) +
            COALESCE(token_detail:cache_write_input::NUMBER, 0)),
        COUNT(DISTINCT REQUEST_ID)))                             AS avg_tokens_per_request,

    ROUND(DIV0(
        SUM(COALESCE(credit_detail:input::FLOAT, 0) +
            COALESCE(credit_detail:output::FLOAT, 0) +
            COALESCE(credit_detail:cache_read_input::FLOAT, 0) +
            COALESCE(credit_detail:cache_write_input::FLOAT, 0)) * 1000000,
        SUM(COALESCE(token_detail:input::NUMBER, 0) +
            COALESCE(token_detail:output::NUMBER, 0) +
            COALESCE(token_detail:cache_read_input::NUMBER, 0) +
            COALESCE(token_detail:cache_write_input::NUMBER, 0))), 4)
                                                                 AS credits_per_1m_tokens
FROM granular
GROUP BY ALL
ORDER BY token_credits DESC;
